apply from: 'gradle/scripts/helpers.gradle'

setDefaultProperty('publish_to_maven', true, false)

publishing {
    repositories {
        maven {
            name = 'outlands'
            url = 'https://maven.outlands.top/releases'
            credentials(PasswordCredentials)
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = propertyString('root_package')
            artifactId = propertyString('mod_id')
            version = project.version
            artifact sourcesJar
            from components.java
        }
    }
}
